[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bedrock-chatbot"
version = "0.1.0"
description = "Reusable AWS Bedrock chatbot client"
authors = [{ name="Shravin Nambiar" }]
dependencies = [
    "boto3>=1.34.0"
]
